Финальное задание по API
eugene-okulik/chebanov pull request #23
Opened 2024-06-28 07:14 UTC by ChebanovAlexsandr

2024-06-28 12:05 UTC, eugene-okulik requested changes
Главное - проверка статуса ответа, особенно когда мы проверяем, что статус 200 - это базовая проверка. Просто если статус не 200, то нет смысла в остальных проверках. Но статус 200 еще не говорит о том, что запрос отработал праильно. Если мы, например, создали мем, то мы хотим убедиться в том, что создалось именно то, что мы создавали. Ведь может прийти статус 200, но мем не сохранился. Можно ли считать такой тест Passed?

2024-06-28 12:05 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/delete_post.py
> +            return None
Не могу найти чем отличаются эти два метода. Тем более, что каждый из них называется как-то непонятно. Один называется удалить удаление (или как-то так), а второй называется удалить не объект.

2024-06-28 12:05 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/tests/test_users_meme.py
> +        print(crete_post_endpoints.post_id)
Принты в тестах - удобно пока возишься с созданием теста, но потом они не нужны.

2024-06-28 12:05 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/endpoint.py
> +        assert self.json["info"]["rating"] == name, GlobalErrorMessages.WRONG_NAME.value
Этот метод проверяет рейтинг где-то в инфо, а называется "проверить что имя ответа правильное"

2024-06-28 18:49 UTC, ChebanovAlexsandr commented
1)Ответ на первый вопрос, сделал валидацию на созданный объект
2)Те методы особо не чем не отличались(это костыли).Так как я не захотел переделывать везде базовую url, она у меня была с  приставкой /meme.А второй метод удаления проверяет возможность удаления объекта который мы не создавали
3)Принты убрал
4)Метод на валидацию rating скопировав с другого теста и не переименовал. Исправил.

2024-06-29 12:34 UTC, eugene-okulik requested changes
Валидация схемы - это тоже общая проверка. Но все же результатом работы каждого ендпоинта является что-то конкретное. При создании мема - результат в том, что создался такой мем, как мы создавали. Хорошо бы это проверить. При изменении мема хорошо бы проверить, что в нем изменилось то, что мы меняли, при удалении мема хорошо бы проверить, что такого мема теперь действительно нет в системе.

2024-07-01 09:42 UTC, eugene-okulik requested changes

2024-07-01 09:42 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/tests/test_users_meme.py
> +    crete_post_endpoints.validate_schema(MemeShema)
Здесь не хватает проверки на то, что мем создался именно с теми значениями, с которыми мы его создавали.

2024-07-01 09:42 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/tests/test_users_meme.py
> +    update_post_endpoints.check_response_info_rating(2)
Здесь не хватает проверки на то, что после изменения те данные, которые мы изменяли действительно изменились.

2024-07-01 09:42 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/endpoint.py
> +        assert self.response.text == f"Meme with id {mem_id} successfully deleted"
Эта проверка непригодна для всех эндпоинтов. Она пригодна только для эндпоинта удаления. Этот метод должен быть в классе эндпоинта удаления.

2024-07-01 09:42 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/get_post.py
> +        """ Метод получения всех постов"""
В этой апи мы не работаем с постами. Хорошо бы называть методы так, чтобы было понятнее что они делают. Второй метод в этом классе называется хорошо.

2024-07-01 09:42 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/put_post.py
> +    def put_update_post(self, mem_id, body, headers=None):
Здесь, судя по названию, этот метод доже изменяет посты, но постов в апишке нет, а есть мемы.

2024-07-01 09:42 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/endpoint.py
> +        assert self.response.text == f"Meme with id {mem_id} successfully deleted"
Ну и этот метод не проверяет, что мем удалён. То, что программа ответила, что удалила мем, не говорит о том, что он удален.

2024-07-01 21:57 UTC, ChebanovAlexsandr commented
Евгений, добрый день. Я вроде уже все исправил, больше уже не знаю что сделать.

2024-07-02 14:37 UTC, eugene-okulik requested changes
Главная фишка этого задания - написать именно автотесты, которые тестируют, что апи работает правильно. В предыдущих заданиях мы просто знакомились с техническими моментами, которые позволят создавать автотесты. А в этом уже создаем автотесты.

2024-07-02 14:37 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/delete_post.py
> +        assert self.response.text == f"Meme with id {mem_id} successfully deleted"
Эта проверка не проверяет удалился ли мем из системы

2024-07-02 14:37 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/endpoint.py
> +        assert self.json['id'] == meme_id, GlobalErrorMessages.WRONG_ID.value
Эта проверка подходит только для ендпоинта, который получает мем по id. Этот метод должен быть в том классе.

2024-07-02 14:37 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/tests/test_users_meme.py
> +    crete_meme_endpoints.check_response_id_is_correct(crete_meme_endpoints.response.json()['id'])
Здесь ты проверяешь, что айди, полученный в ответе равен айди, полученному в ответе. Т.е. ничего не проверяешь.

2024-07-02 14:37 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/tests/test_users_meme.py
> +    crete_meme_endpoints.check_response_id_is_correct(crete_meme_endpoints.response.json()['id'])
В этом тесте должно проверяться, что та информация которую мы отправляли при создании мема, сохранилась именно такой как мы отправляли. То есть проверить text, url, tags, info.

2024-07-02 14:37 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/tests/test_users_meme.py
> +    update_meme_endpoints.check_response_info_rating(5)  # Вот проверка на обновленное значение
В этом тесте нам важно проверить, что после отправки изменений, вся информация сохранилась именно такой, как мы отправляли.

2024-07-05 09:48 UTC, eugene-okulik approved these changes
Уже все значительно лучше, но еще остались моменты, например, с названиями: create_post, delete_post, ... Эта апи не хранит посты. Та апи, на которой я всё демонстировал в видео, хранит посты. Это типа апи соцсети, а в соцсети есть посты и вот та апи их хранит. А эта апи хранит мемы. Названия вносят путаницу.  
В классе Endpoint слишком много методов для проверки. Причем не все из них подходят для всех эндпоинтов. Хорошо бы подумать как сделать такую структуру, где всё не смешивалось бы в одном классе.  
Круто, что разобрался в BeautifulSoup, хоть он здесь и не нужен.

2024-07-05 09:48 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/delete_post.py
> +                                          "manually please check your spelling and try again."
Вместо этого можно было проверить, что вернулась ошибка 404

2024-07-05 09:48 UTC, eugene-okulik commented on homework/alexsand_chebanov/test_api_final_Lesson_23_chebanovau/endpoints/endpoint.py
> +        assert self.json['id'] == meme_id, GlobalErrorMessages.WRONG_ID.value
Этот метод нужно перенести в класс GetPost

2024-07-05 09:48 UTC, merged